server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  accessLogEnabled:    true

logger:
  level: "all"
  stdout: true
  path:    "logs/default"
  ctxKeys: ["RequestId"]

database:
  logger:
    path:    "logs/sql"
    level:   "all"
    stdout:  true
    ctxKeys: ["RequestId"]
  default:
    link:   "sqlite:sqlite.db"
    debug:  true

