// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package dto

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Users is the golang structure of table users for DAO operations like Where/Data.
type Users struct {
	g.Meta   `orm:"table:users, dto:true"`
	Id       interface{} //
	Name     interface{} //
	Departid interface{} //
	NickName interface{} //
	Phone    interface{} //
	Uid      interface{} //
}
