// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Users is the golang structure for table users.
type Users struct {
	Id       int    `json:"id"       ` //
	Name     string `json:"name"     ` //
	Departid int    `json:"departid" ` //
	NickName string `json:"nickName" ` //
	Phone    string `json:"phone"    ` //
	Uid      int    `json:"uid"      ` //
}
