// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"go-study/kratos-websocket/app/admin/internal/conf"
	"go-study/kratos-websocket/app/admin/internal/server"
	"go-study/kratos-websocket/app/admin/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, registry *conf.Registry, auth *conf.Auth, logger log.Logger) (*kratos.App, func(), error) {
	adminService := service.NewAdminService(logger)
	httpServer := server.NewHTTPServer(confServer, auth, logger, adminService)
	grpcServer := server.NewGRPCServer(confServer, logger, adminService)
	websocketServer := server.NewWebsocketServer(confServer, logger, adminService)
	app := newApp(logger, httpServer, grpcServer, websocketServer)
	return app, func() {
	}, nil
}
